import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d8dadc",
        "secondary-fixed": "#d8e2ff",
        "on-primary-fixed": "#00164e",
        surface: "#f7f9fb",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#b6c4ff",
        "tertiary-fixed-dim": "#ffb95f",
        "on-primary-container": "#90a8ff",
        "tertiary-container": "#5c3800",
        "on-background": "#191c1e",
        "on-surface-variant": "#444651",
        "secondary-container": "#2170e4",
        "error-container": "#ffdad6",
        "outline-variant": "#c5c5d3",
        secondary: "#0058be",
        primary: "#00236f",
        "on-secondary": "#ffffff",
        tertiary: "#3e2400",
        "on-secondary-fixed-variant": "#004395",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed-variant": "#264191",
        "on-secondary-container": "#fefcff",
        outline: "#757682",
        "on-tertiary-fixed": "#2a1700",
        "on-secondary-fixed": "#001a42",
        "on-tertiary-container": "#ef9900",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-low": "#f2f4f6",
        "surface-container-highest": "#e0e3e5",
        "surface-container": "#eceef0",
        "tertiary-fixed": "#ffddb8",
        "surface-tint": "#4059aa",
        background: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        error: "#ba1a1a",
        "primary-container": "#1e3a8a",
        "primary-fixed": "#dce1ff",
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
};

export default config;

